appname = myGymPal
httpaddr = localhost
httpport = 8080
runmode = dev

# Sessions
sessionon = true
sessionname = mygympal_session
sessiongcmaxlifetime = 2592000
sessioncookielifetime = 2592000
sessionprovider = postgresql
sessionproviderconfig = user=postgres password=postgres dbname=mygympal host=localhost port=5432 sslmode=disable

# PostgreSQL connection
db_driver = postgres
db_host = localhost
db_port = 5432
db_name = mygympal
db_user = postgres
db_password = postgres
db_sslmode = disable
